#Override containers for dev
version: "2.4"
services:

  reverse_proxy:
    volumes:
      - .local/nginx:/data

  ui:
    command: yarn start
    mem_limit: 1g
    stdin_open: true
    volumes:
      - ./ui:/app

  server:
    command: ["yarn", "debug"]
    ports:
      - "127.0.0.1:9229:9229" #Allows remote debugging
    volumes:
      - .local/server:/data
      - ./server/src:/app/src
    environment:
      - SIRIUS_ENV=dev
      - SIRIUS_LOG_LEVEL=debug

  mongodb:
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - .local/mongodb:/data
